### PR TITLE
Add required permission for private repo

### PR DESCRIPTION
**Pull request by gaqzi**
Thanks for a great blog post! I noticed that the permission is slightly different 
for private repos and this is the trial and error that made it work on my end. :) 

Not entirely sure why this works as-is on a public repo and why 
it has to be added for a private, but that's the case. 🤷

I also made this step to approve the PR because my private repos require 
at least one approving review for it to merge. But I wasn't sure about adding it
to the post so I'll just mention it here. :)

```yaml
      - name: Approve the PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### CODE REVIEW

**Comment by gaqzi** [comment]
Okay, was a bit too fast on solving the need for an approval. It works for repos that only require _an approval_ but not those using code owners. Trying to find a solution for that, so it's not complete. :)

**Comment by gaqzi** [comment]
Think I found a way skipping the approval and instead relying on "after these workflows finishes successfully, then merge bypassing approval." Will try that out some other day. I will leave an update if I figure it out :)

**Comment by rednafi** [comment]
Hi, thanks for trying it out. I'll admit, I haven't tested it in a private repo. Also, the GitHub docs don't help here. I'll try it out in a private repo and see how this goes.

**Comment by rednafi** [comment]
Merging this as is. Currently it's working for private repos and I think it's good enough as is.

**Pull request merged**
